export const aoc = require('../assets/aoc.jpg')
export const saavedra = require('../assets/saavedra.jpg')
export const food = require('../assets/food.gif')
export const gerry = require('../assets/gerry.jpg')
export const az1 = require('../assets/amazon1.png')
export const az2 = require('../assets/amazon2.png')
export const az3 = require('../assets/amazon3.png')
export const az4 = require('../assets/amazon4.png')
